combination:
  resonance: [D2_2460, D3_2750, D1_2760, D2_2957, PHSP]
  resonance_main: [D2_2460, D3_2750, D1_2760]
  combination_veto:
    - [D3_2750, D1_2760]
    - [D3_2750, D1_2760, PHSP]
    - [D2_2460, D3_2750, D1_2760]
  combination_focus: [D2_2460, D3_2750, D1_2760]
  # combination_focus: []

# combination:
#   resonance: [D2_2460, PHSP]
#   resonance_main: [D2_2460]
#   combination_veto: []
#   combination_focus: [D2_2460, PHSP]

data:
  # sample: [4660, 4680, 4700, 4750, 4780, 4840]
  sample: [4680]
  # sample: [4780]
  # sample: [4420]
  dat_order: [B, C, D]
  data: ['/hpcfs/bes/gpupwa/jingmq/DDbarPi-PWA/data_base/data_sample/data.dat']
  phsp: ['/hpcfs/bes/gpupwa/jingmq/DDbarPi-PWA/data_base/data_sample/phsp.dat']
  bg: ['/hpcfs/bes/gpupwa/jingmq/DDbarPi-PWA/data_base/data_sample/bkg.dat']
  bg_weight: ['/hpcfs/bes/gpupwa/jingmq/DDbarPi-PWA/data_base/data_sample/bkg_weight.dat']
  negtive_idx: []
  random_z: False

decay:
  A:
    - [R_BC, D]
    - [R_BD, C]
    - [R_CD, B]
  R_BC: [B, C]
  R_BD: [B, D]
  R_CD: [C, D]

particle:
  $top:
    A: {J: 1, P: -1, spins: [-1, 1]}
  $finals:
    B: {J: 0, P: -1}
    C: {J: 0, P: -1}
    D: {J: 0, P: -1}
  $include: /hpcfs/bes/gpupwa/jingmq/DDbarPi-PWA/data_base/Resonances.yml

constrains:
  particle: null
  decay: null
  fix_var:
    'A->D2_2460.CD2_2460->B.D_total_0i': 0.0

plot:
  mass:
    R_BC: { display: "$M_{BC}$" }
    R_BD: { display: "$M_{BD}$" }
    R_CD: { display: "$M_{CD}$" }
  2Dplot:
    m_R_CD & m_R_BC:
      display: "$M_{CD}$ vs $M_{BC}$"
      plot_figs: ["data", "sideband", "fitted"]
    m_R_CD & m_R_BD:
      display: "$M_{CD}$ vs $M_{BD}$"
      plot_figs: ["data", "sideband", "fitted"]
    m_R_BC & m_R_BD:
      display: "$M_{BC}$ vs $M_{BD}$"
      plot_figs: ["data", "sideband", "fitted"]
  angle:
    A/R_CD:
      alpha:
        display: "$\\phi_{CD}$"
      cos(beta):
        display: "$\\cos(\\theta_{CD})$"
        range: [-1, 1]
    A/R_BD:
      alpha:
        display: "$\\phi_{BD}$"
      cos(beta):
        display: "$\\cos(\\theta_{BD})$"
    A/R_BC:
      alpha:
        display: "$\\phi_{BC}$"
      cos(beta):
        display: "$\\cos(\\theta_{BC})$"
    R_BC/B:
      alpha:
        display: "$\\phi_{B/BC}$"
      cos(beta):
        display: "$\\cos(\\theta_{B/BC})$"
    R_CD/C:
      alpha:
        display: "$\\phi_{C/CD}$"
      cos(beta):
        display: "$\\cos(\\theta_{C/CD})$"
    R_BD/B:
      alpha:
        display: "$\\phi_{B/BD}$"
      cos(beta):
        display: "$\\cos(\\theta_{B/BD})$"

scan:
    # resonance: 'D2_2460'
    # mass: [2.4660, 2.4700, 40]
    # width: [0.040, 0.045, 50]
    # resonance: 'D2_2460p'
    # mass: [2.4600, 2.4800, 20]
    # width: [0.030, 0.052, 22]
    # resonance: 'D3_2750'
    # mass: [2.7400, 2.8000, 60]
    # width: [0.040, 0.100, 60]
    resonance: 'D3_2750p'
    mass: [2.7400, 2.8000, 60]
    width: [0.040, 0.100, 60]
