combination:
  resonance: [D2_2460, D3_2750, D1_2760, D1_2600]
  resonance_main: [D2_2460, D3_2750]
  combination_veto: [(D2_2460, D1_2600), (D2_2460, D1_2750)]
  # combination_focus: [D2_2460, D3_2750, D1_2750]
  combination_focus: []

data:
  sample: [4660, 4680, 4700]
  dat_order: [B, C, D]
  data: ['/hpcfs/bes/gpupwa/jingmq/data_base/data_sample/data.dat']
  phsp: ['/hpcfs/bes/gpupwa/jingmq/data_base/data_sample/phsp.dat']
  bg: ['/hpcfs/bes/gpupwa/jingmq/data_base/data_sample/bkg.dat']
  bg_weight: ['/hpcfs/bes/gpupwa/jingmq/data_base/data_sample/bkg_weight.dat']
  negtive_idx: []
  random_z: False

decay:
  A:
    - [R_BC, D]
    - [R_BD, C]
    - [R_CD, B]
  R_BC: [B, C]
  R_BD: [B, D]
  R_CD: [C, D]

particle:
  $top:
    A: {J: 1, P: -1, spins: [-1, 1]}
  $finals:
    B: {J: 0, P: -1}
    C: {J: 0, P: -1}
    D: {J: 0, P: -1}
  $include: /hpcfs/bes/gpupwa/jingmq/data_base/Resonances.yml

constrains:
  particle: null
  decay: null
  fix_var:
    'A->D2_2460.CD2_2460->B.D_total_0i': 0.0
